import type { FormatPlan, Storyboard } from "@velocity/contracts";

/**
 * The four formats (build script 8.5), each deciding which activities
 * actually run and with what shot specs. This is real dispatch logic,
 * consumed by resolveAssets — not a stub, though the shots it describes
 * are of course generated by stub providers until real vendor credentials
 * land (see docs/steps/STEP-08.md).
 */

const TARGET_RESOLUTION = "1080x1920";

function combineVoiceover(storyboard: Storyboard): string {
  return storyboard.scenes
    .map((s) => s.voiceoverLine)
    .filter((line): line is string => Boolean(line))
    .join(" ");
}

/** AI UGC talking head — persona reference image -> image-to-video with lip-sync + VO. */
export function buildAiUgcFormatPlan(storyboard: Storyboard, referenceImageUrl: string | null): FormatPlan {
  const script = combineVoiceover(storyboard);
  return {
    format: "ai_ugc",
    shots: storyboard.scenes.map((scene, i) => ({
      shotIndex: i,
      durationSec: scene.durationMs / 1000,
      prompt: scene.visualDirective,
      referenceImageUrl,
      resolution: TARGET_RESOLUTION,
      requiresLipSync: true,
      requiresImageToVideo: true,
    })),
    voiceover: script ? { script, voiceId: "default" } : null,
    outputsImageSet: false,
    targetDurationSec: storyboard.scenes.reduce((sum, s) => sum + s.durationMs, 0) / 1000,
    targetResolution: TARGET_RESOLUTION,
  };
}

/** Slideshow — generated images + per-slide overlay text, exported as an image set (TikTok photo posts are URL-pull only, build script 8.5). */
export function buildSlideshowFormatPlan(storyboard: Storyboard): FormatPlan {
  return {
    format: "slideshow",
    shots: storyboard.scenes.map((scene, i) => ({
      shotIndex: i,
      durationSec: scene.durationMs / 1000,
      prompt: scene.visualDirective,
      referenceImageUrl: null,
      resolution: TARGET_RESOLUTION,
      requiresLipSync: false,
      requiresImageToVideo: false,
    })),
    voiceover: null,
    outputsImageSet: true,
    targetDurationSec: storyboard.scenes.reduce((sum, s) => sum + s.durationMs, 0) / 1000,
    targetResolution: TARGET_RESOLUTION,
  };
}

/** Hook + demo — talking hook cut to product screen capture with motion. Only the first (hook) shot needs lip-sync. */
export function buildHookDemoFormatPlan(storyboard: Storyboard, referenceImageUrl: string | null): FormatPlan {
  const script = combineVoiceover(storyboard);
  return {
    format: "hook_demo",
    shots: storyboard.scenes.map((scene, i) => ({
      shotIndex: i,
      durationSec: scene.durationMs / 1000,
      prompt: scene.visualDirective,
      referenceImageUrl: i === 0 ? referenceImageUrl : null,
      resolution: TARGET_RESOLUTION,
      requiresLipSync: i === 0,
      requiresImageToVideo: i === 0,
    })),
    voiceover: script ? { script, voiceId: "default" } : null,
    outputsImageSet: false,
    targetDurationSec: storyboard.scenes.reduce((sum, s) => sum + s.durationMs, 0) / 1000,
    targetResolution: TARGET_RESOLUTION,
  };
}

/** Meme — template + generated caption bar. A single still image, no voiceover. */
export function buildMemeFormatPlan(storyboard: Storyboard): FormatPlan {
  const firstScene = storyboard.scenes[0]!;
  return {
    format: "meme",
    shots: [
      {
        shotIndex: 0,
        durationSec: firstScene.durationMs / 1000,
        prompt: firstScene.visualDirective,
        referenceImageUrl: null,
        resolution: TARGET_RESOLUTION,
        requiresLipSync: false,
        requiresImageToVideo: false,
      },
    ],
    voiceover: null,
    outputsImageSet: true,
    targetDurationSec: firstScene.durationMs / 1000,
    targetResolution: TARGET_RESOLUTION,
  };
}

export function buildFormatPlan(
  format: FormatPlan["format"],
  storyboard: Storyboard,
  referenceImageUrl: string | null,
): FormatPlan {
  switch (format) {
    case "ai_ugc":
      return buildAiUgcFormatPlan(storyboard, referenceImageUrl);
    case "slideshow":
      return buildSlideshowFormatPlan(storyboard);
    case "hook_demo":
      return buildHookDemoFormatPlan(storyboard, referenceImageUrl);
    case "meme":
      return buildMemeFormatPlan(storyboard);
  }
}
