// @ts-check
import tseslint from "@typescript-eslint/eslint-plugin";
import tsparser from "@typescript-eslint/parser";

export default [
  {
    ignores: [
      "**/node_modules/**",
      "**/dist/**",
      "**/.next/**",
      "**/.turbo/**",
      "**/out/**",
      // Auto-generated by `next build`/`next dev`, never hand-edited (its
      // own header says so) — Next.js's own project template excludes it
      // from lint for the same reason. Next 15.5's new statically-typed-
      // routes feature added a third `/// <reference>` line here that
      // trips @typescript-eslint/triple-slash-reference; the file's
      // shape is entirely Next's to manage, not this repo's lint rules'.
      "**/next-env.d.ts",
    ],
  },
  {
    files: ["**/*.ts", "**/*.tsx"],
    languageOptions: {
      parser: tsparser,
      parserOptions: {
        sourceType: "module",
      },
    },
    plugins: {
      "@typescript-eslint": tseslint,
    },
    rules: {
      ...tseslint.configs.recommended.rules,
      "@typescript-eslint/no-unused-vars": ["warn", { argsIgnorePattern: "^_" }],
    },
  },
];
