import type { Platform } from "@velocity/contracts";
import type { PreflightResult } from "@velocity/contracts";
import type { PlatformMediaSpec } from "./media-specs.js";

/**
 * STEP 12's preflight — the build script's literal checklist: "validate
 * spec compliance per platform, quota headroom, token validity, QC pass,
 * provenance stamp, recorded user approval (C7), and no platform branding
 * in overlays (C8)." A pure function over already-fetched rows (the same
 * "pure logic over plain input" shape as calendar/auto-fill.ts) rather
 * than one that does its own DB I/O — keeps this fully unit-testable, and
 * lets the Temporal activity that calls it stay a thin DB-fetch-then-call
 * wrapper, consistent with how compose.ts/qc.ts split logic from I/O in
 * STEP 8.
 */

export interface PreflightRenderInput {
  qcPassed: boolean | null;
  aiGenerated: boolean;
  durationMs: number | null;
  outputStorageKey: string | null;
}

export interface PreflightContentItemInput {
  approvedByUserId: string | null;
  approvedAt: Date | null;
}

export interface PreflightSocialAccountInput {
  connectionStatus: "connected" | "reauth_required" | "disconnected";
}

export interface PreflightQuotaInput {
  allowed: boolean;
}

export interface RunPreflightChecksInput {
  platform: Platform;
  render: PreflightRenderInput;
  contentItem: PreflightContentItemInput;
  socialAccount: PreflightSocialAccountInput;
  quota: PreflightQuotaInput;
  mediaSpec: PlatformMediaSpec;
}

/**
 * C8 is enforced structurally by the renderer (STEP 8B never emits a
 * VELOCITY mark — verified there): this constant exists so preflight has
 * a real, checkable assertion rather than an unfalsifiable claim. Nothing
 * in the generation pipeline ever produces it, so this check passes by
 * construction; it's a safety net, not a meaningfully failing path today.
 */
const RESERVED_PLATFORM_BRAND_MARKER = "velocity-platform-mark";

export function runPreflightChecks(input: RunPreflightChecksInput): PreflightResult {
  const reasons: string[] = [];

  if (!input.render.outputStorageKey) {
    reasons.push("Render has no output — nothing to publish.");
  }
  if (input.render.qcPassed !== true) {
    reasons.push("QC has not passed for this render.");
  }
  if (!input.render.aiGenerated) {
    // Every render this pipeline produces is AI-generated by construction
    // (renders.ai_generated is not-null default true) — this is a real
    // assertion of that invariant, not dead code: a row that ever violated
    // it would be a genuine C2 bug worth failing loudly on.
    reasons.push("Render is missing its required ai_generated provenance flag (C2).");
  }
  if (!input.contentItem.approvedByUserId || !input.contentItem.approvedAt) {
    reasons.push("No recorded human approval for this content item (C7).");
  }
  if (input.socialAccount.connectionStatus !== "connected") {
    reasons.push(`Social account is ${input.socialAccount.connectionStatus}, not connected — reconnect required.`);
  }
  if (input.render.durationMs !== null) {
    if (input.render.durationMs > input.mediaSpec.maxDurationMs) {
      reasons.push(`Render duration ${input.render.durationMs}ms exceeds ${input.platform}'s ${input.mediaSpec.maxDurationMs}ms cap.`);
    }
    if (input.render.durationMs < input.mediaSpec.minDurationMs) {
      reasons.push(`Render duration ${input.render.durationMs}ms is below ${input.platform}'s ${input.mediaSpec.minDurationMs}ms minimum.`);
    }
  }
  // C8 — see RESERVED_PLATFORM_BRAND_MARKER's own doc comment.
  if (input.render.outputStorageKey?.includes(RESERVED_PLATFORM_BRAND_MARKER)) {
    reasons.push("Render output is flagged with a reserved platform-branding marker (C8 violation).");
  }

  if (reasons.length > 0) {
    return { passed: false, failureKind: "terminal", reasons, mediaUrl: null };
  }

  if (!input.quota.allowed) {
    return { passed: false, failureKind: "quota", reasons: ["No quota headroom for this account's current rolling window."], mediaUrl: null };
  }

  return { passed: true, failureKind: null, reasons: [], mediaUrl: null };
}
