import { boolean, jsonb, numeric, pgTable, text, timestamp, uuid } from "drizzle-orm/pg-core";
import { EMBEDDING_DIMENSIONS, idColumn, softDelete, timestamps, vector, workspaceIdColumn } from "./_helpers";
import { angles, personas, trendBlueprints } from "./content-planning";
import { contentFormatEnum, contentItemStatusEnum } from "./enums";
import { workspaces } from "./tenancy";

/**
 * Tier-1, LLM-only unit that fills the Blitz queue (STEP 8.2, STEP 9).
 * `aiGenerated` is `boolean not null default true` — every concept produced
 * by this pipeline is AI-generated by construction, so the column exists to
 * make that fact queryable/auditable, not to record an unknown.
 */
export const contentConcepts = pgTable("content_concepts", {
  id: idColumn(),
  workspaceId: workspaceIdColumn().references(() => workspaces.id),
  angleId: uuid("angle_id")
    .notNull()
    .references(() => angles.id),
  format: contentFormatEnum("format").notNull(),
  personaId: uuid("persona_id").references(() => personas.id),
  blueprintId: uuid("blueprint_id").references(() => trendBlueprints.id),
  hook: text("hook").notNull(),
  previewAssetStorageKey: text("preview_asset_storage_key"),
  predictedScore: numeric("predicted_score", { precision: 5, scale: 4 }),
  aiGenerated: boolean("ai_generated").notNull().default(true),
  embedding: vector("embedding", { dimensions: EMBEDDING_DIMENSIONS }),
  ...timestamps(),
  ...softDelete(),
});

export const storyboards = pgTable("storyboards", {
  id: idColumn(),
  workspaceId: workspaceIdColumn().references(() => workspaces.id),
  contentConceptId: uuid("content_concept_id")
    .notNull()
    .references(() => contentConcepts.id),
  scenes: jsonb("scenes").$type<
    Array<{
      durationMs: number;
      visualDirective: string;
      onScreenText?: string;
      voiceoverLine?: string;
      bRollQuery?: string;
      transition?: string;
    }>
  >()
    .notNull()
    .default([]),
  ...timestamps(),
});

/**
 * One row per TextPlan (STEP 8B.2). `plan` stores the full validated JSON
 * object — the TextPlanSchema in @velocity/text-engine is the source of
 * truth for its shape; this column is intentionally untyped jsonb rather
 * than duplicating that schema's structure into SQL columns. The link to
 * `content_items` is one-directional (content_items.text_plan_id -> here)
 * to avoid a circular FK pair; look up a text plan's content item with a
 * reverse query rather than a back-reference column.
 */
export const textPlans = pgTable("text_plans", {
  id: idColumn(),
  workspaceId: workspaceIdColumn().references(() => workspaces.id),
  version: text("version").notNull().default("1.0"),
  plan: jsonb("plan").notNull(),
  ...timestamps(),
});

export const hookVariants = pgTable("hook_variants", {
  id: idColumn(),
  workspaceId: workspaceIdColumn().references(() => workspaces.id),
  textPlanId: uuid("text_plan_id")
    .notNull()
    .references(() => textPlans.id),
  text: text("text").notNull(),
  pattern: text("pattern").notNull(),
  predictedCtr: numeric("predicted_ctr", { precision: 5, scale: 4 }),
  embedding: vector("embedding", { dimensions: EMBEDDING_DIMENSIONS }),
  ...timestamps(),
});

/**
 * Tier-2 unit — an approved (swiped-right) concept progressing toward a
 * real render. `status` is the CONCEPT -> ... -> PUBLISHED lifecycle from
 * STEP 9. `aiGenerated` and the approval fields are C2/C7 evidence.
 */
export const contentItems = pgTable("content_items", {
  id: idColumn(),
  workspaceId: workspaceIdColumn().references(() => workspaces.id),
  contentConceptId: uuid("content_concept_id")
    .notNull()
    .references(() => contentConcepts.id),
  textPlanId: uuid("text_plan_id")
    .notNull()
    .references(() => textPlans.id),
  status: contentItemStatusEnum("status").notNull().default("concept"),
  aiGenerated: boolean("ai_generated").notNull().default(true),
  approvedByUserId: uuid("approved_by_user_id"), // set on swipe-right / manual approval — C7 evidence
  approvedAt: timestamp("approved_at", { withTimezone: true }),
  ...timestamps(),
  ...softDelete(),
});
